### ISSUE TITLE
Site is using Cookies _ororo_session etc. for validation

### ISSUE THREAD

**Issue by rishabhgpt** [OzieWest/xbmc-plugin-ororo-tv#1]
Following the HTTP header request sent from browser:

```
Accept  text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
```

Accept-Encoding gzip, deflate, sdch
Accept-Language en-US,en;q=0.8,es;q=0.6,hi;q=0.4,ru;q=0.2
Cookie  video=true;
_ga=GA1.2.339709105.1424606219;
_ororo_session=RlVKU2JUYWkyUzIvQUJGMTMxZ0JKcExzM2pxSWdzcEdCWEw3RlNDbmh5UkpaeDFqeC9jR1Y1WGNJSHgzazVhLzJFaGNLOG4wR0hsdlBHcGtQZjBhTHY3ZHB1WVdralB5UjdzNFdJQVlmdU5lcG4xN2dLT3c2WTNvRFpNNWtaMGRsV2V2enFXT0hqZTBoNzJPV3JiaGNMWHFOcFUzVmV6VkthQTlGaFEzYlFLeDg3bG8wZWxydTF4eHBnY1Z5VmF1a1VsNVJsQU9ySlhMYTNXR1VGNzREZmV6aURUMzBPeXRTWENBM2psM0dzcz0tLXc0VjlBZjUrV3hlSTUxSTRDTEk0RHc9PQ%3D%3D--c030986d158d66528261ff4297006f14e1fc0d87
DNT 1
User-Agent  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrom...

Can you use this to emulate the same thing from script. I tried but failed

**Comment by OzieWest** [comment]
Thanks, I'll check it on next weekends

**Comment by rishabhgpt** [comment]
closing as not relavent now.
